//this is the list of words, taken from 'recent' (within the last 20 years or so) additions to the Merriam Webster dictionary. In the future I'd like to use the MW's API, and perhaps target slang words specifically by date of of first known use in the JSON data, or by some other category (maybe they have an 'informal usage' category but I didn't see it in their documentation). The API requires a key and I didn't want to deal with that in such a short timeframe for this project, but web scraping (by going through the slang tag on their website) could be an alternative once I figure out how to do that....

const slang_list = [
  'adorkable',     'adulting',
  'altcoin',       'amirite',        'beast mode',
  'binge watch',   'binge watched',  'binge watching',
  'binge-watch',   'binge-watched',  'binge-watching',
  'bingewatch',    'bingewatched',   'bingewatching',
  'blogosphere',   'burner account', 'cancel culture',
  'cheugy',        'chonky',         'clap back',
  'clapback',      'click through',  'click-through',
  'clickbait',     'clickbaited',    'clickbaiting',
  'clickstream',   'clickstreams',   'clickthrough',
  'copypasta',     'copypastas',     'crowdfund',
  'crowdfund',     'crowdfunding',   'cutscene',
  'doom scroll',   'doomscroll',     'doomscrolled',
  'doomscrolling', 'downvote',       'dox',
  'dumbphone',     'epic fail',      'esport',
  'esports',       'filter bubble',  'finsta',
  'flash mob',     'FOMO',           'FPS',       
  'FYP',           'for you page',   'foryoupage',
  'fwiw',          'girlboss',       'goated',
  'hot take',      'icymi',          'idgaf',
  'idk',           'incel',          'inspo',
  'jack in',       'jacked in',      'jorts',
  'jump scare',    'jump scares',    'jumpscare',
  'jumpscares',    'laggy',          'level up',
  'life hack',     'lol',            'manspreading',
  'maskne',        'meatspace',      'meme stock',
  'metaverse',     'mic drop',       'microblog',
  'microblogging', 'mid',            'nepo babies',
  'nepo baby',     'nepobabies',     'nepobaby',
  'nerf',          'nerfed',         'nerfing',
  'nerfs',         'ngl',            'non-playable character',
  'npc',           'on fleek',       'photobomb',
  'photobombed',   'photobombing',   'pwn',
  'quiet quit',    'rage quit',      'ragequit',
  'retweet',       'review bombing', 'rizz',
  'rizzed',        'selfie',         'sext',            
  'sexting',       'shadow ban',     'shadow banned',
  'shadowban',     'shadowbanned',   'smishing',
  'speedrun',      'speedrunning',   'speedruns',      
  'sponcon',       'subtweet',       'subtweeted',    
  'subtweeting',   'super spreading','super-spreading', 
  'sus',           'tdlr',           'tfw',             
  'thirst trap',   'tl;dr',          'touch grass',     
  'touching grass','truther',        'ttyl',            
  'tweetstorm',    'unlike',         'upvote',          
  'vlog',          'vlogger',        'vlogging',       
  'yeet',          'zoomer'
  ]

  //It would be cool to add an options page where users could input their own words and have them added to the extension's slang list